### PR TITLE
Update for Dalamud API 9

### PR DESCRIPTION
**Pull request by SHOEGAZEssb**
Hey, I updated this plugin for API 9 + made some functional changes, since previewing glamor was broken.

### CODE REVIEW

**Comment by DrBob17** [comment]
Hey, how do I use this updated version?

**Comment by SHOEGAZEssb** [comment]
> Hey, how do I use this updated version?

You will have to wait until @Seventhxiv merges this pull request and updates the plugin

**Comment by DrBob17** [comment]
I see. Cool thanks for the heads up

**Comment by Seventhxiv** [comment]
Thanks, I will need a bit of time to get to this.

**Pull request merged**
